version: '2.0'

services:
  app:
    build: .
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG=broodminder
      - INFLUXDB_BUCKET=broodminder
      - INFLUXDB_TOKEN=asdf
    ports:
      - 5000:5000
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.broodminder.rule=Host(`app.yourdomain.com`) && PathPrefix(`/broodminder/`)"
      - "traefik.http.routers.broodminder.entrypoints=internal"
      - "traefik.http.routers.broodminder.tls=true"
      - "traefik.http.routers.broodminder.tls.certResolver=letsEncrypt"
      - "traefik.docker.network=traefik"
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
 
networks:
  traefik:
    external: true
